# Generated by Django 5.2.8 on 2025-11-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_services_name', models.CharField(max_length=100)),
                ('main_services_description', models.TextField(blank=True, null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_services', to='services.gender')),
            ],
            options={
                'unique_together': {('gender', 'main_services_name')},
            },
        ),
        migrations.CreateModel(
            name='Child_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_service_name', models.CharField(default='Default Service', max_length=100)),
                ('child_service_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('duration', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.gender')),
                ('main_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_services', to='services.mainservices')),
            ],
        ),
    ]
