# Generated by Django 5.2.8 on 2025-11-10 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_category_service_duration_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='gender',
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('gender', 'name')},
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='gender',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.gender'),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Default Service', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
