# Generated by Django 5.2.8 on 2025-11-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyslot',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
